[profile.default]
src = "src"
test = "test"
out = "out"
allow_paths = [
  # pnpm symlinks to the project root's node_modules
  "../../node_modules",
]
extra_output_files = [
  "abi",
  "evm.bytecode"
]
fs_permissions = [{ access = "read", path = "./"}]
libs = ["node_modules", "lib"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
